spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/holiday
    username: root
    password: p@ssword
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
